on:
  pull_request:
  push:
    branches: [master]

jobs:
  lints:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Clone repo

      - uses: DeterminateSystems/nix-installer-action@main
        name: Install Nix

      - uses: DeterminateSystems/magic-nix-cache-action@main
        name: Setup Nix cache

      - name: Build application using Nix
        run: nix build .
